"""
Rebuild the FAISS vector index from PostgreSQL.

Use when storage/faiss/video.index (or its metadata.json sidecar) is
lost or corrupted but the `embeddings` table in Postgres is intact -
every row already stores its deterministic vector_id (see
ai.embedding.embedder.Embedder._build_vector_id) and the original
chunk_text, so the index can be regenerated by re-encoding each
chunk's text and re-inserting it under the exact vector_id it already
had. No other table changes, and no existing vector_id ever changes,
so RAG/search code needs no changes afterward.

Usage (from backend/, with PYTHONPATH set so `app`/`ai` are
importable - see scripts/run_backend.sh for the same convention):

    python scripts/rebuild_faiss_index.py

Safe to run against an empty `embeddings` table too (produces an
empty, valid index). Takes the same file lock
VectorStore.add()/replace() use, so it will not race a live
add/replace happening at the same time - but you should still stop
the worker (or at least pause processing) before running this, since
a rebuild started mid-reprocessing would only see whatever rows exist
in Postgres at that moment.
"""
import logging

import numpy as np

from ai.embedding.embedder import Embedder
from ai.embedding.faiss_lock import FileLock
from ai.embedding.index_builder import IndexBuilder
from ai.embedding.index_metadata import IndexMetadata
from app.database.session import SessionLocal
from app.repositories.embedding import EmbeddingRepository

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger("rebuild_faiss_index")

DIMENSION = 1024


def _load_embedding_rows():
    db = SessionLocal()
    try:
        return EmbeddingRepository(db).get_all()
    finally:
        db.close()


def rebuild() -> None:
    rows = _load_embedding_rows()

    if not rows:
        logger.warning(
            "No rows found in the embeddings table - rebuilding an "
            "empty FAISS index. If this is unexpected, check "
            "DATABASE_URL before proceeding."
        )

    logger.info("Re-encoding %s chunk(s)...", len(rows))

    builder = IndexBuilder(dimension=DIMENSION)
    lock_path = builder.index_path.with_name(builder.index_path.name + ".lock")

    with FileLock(lock_path):
        index = builder.create_index()
        metadata = IndexMetadata()
        metadata.mapping = {}
        metadata.reverse = {}

        if rows:
            embedder = Embedder()
            texts = [row.chunk_text for row in rows]
            result = embedder.model.encode(texts)
            vectors = np.asarray(result["dense_vecs"], dtype=np.float32)

            index.add(vectors)

            for position, row in enumerate(rows):
                metadata.add(index=position, vector_id=row.vector_id)

        builder.save_index(index)
        metadata.save()

    logger.info(
        "FAISS index rebuilt: %s vector(s) written to %s",
        index.ntotal,
        builder.index_path,
    )


if __name__ == "__main__":
    rebuild()
