"""add cascade delete for transcript

Revision ID: 0baa5f1bac56
Revises: 579f467ba0f7
Create Date: 2026-07-19 00:19:43.657559

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0baa5f1bac56'
down_revision: Union[str, Sequence[str], None] = '579f467ba0f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('transcripts_video_id_fkey'), 'transcripts', type_='foreignkey')
    op.create_foreign_key(None, 'transcripts', 'videos', ['video_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transcripts', type_='foreignkey')
    op.create_foreign_key(op.f('transcripts_video_id_fkey'), 'transcripts', 'videos', ['video_id'], ['id'])
    # ### end Alembic commands ###
