"""add cascade delete for video embeddings

Revision ID: 21618627fcc5
Revises: a206a1e6cff1
Create Date: 2026-07-30 00:43:00.934013

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '21618627fcc5'
down_revision: Union[str, Sequence[str], None] = 'a206a1e6cff1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('embeddings_video_id_fkey'), 'embeddings', type_='foreignkey')
    op.create_foreign_key(None, 'embeddings', 'videos', ['video_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'embeddings', type_='foreignkey')
    op.create_foreign_key(op.f('embeddings_video_id_fkey'), 'embeddings', 'videos', ['video_id'], ['id'])
    # ### end Alembic commands ###
