"""add cascade delete for processing jobs

Revision ID: 579f467ba0f7
Revises: aea3aec5b92e
Create Date: 2026-07-18 23:12:13.952484

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '579f467ba0f7'
down_revision: Union[str, Sequence[str], None] = 'aea3aec5b92e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('processing_jobs_video_id_fkey'), 'processing_jobs', type_='foreignkey')
    op.create_foreign_key(None, 'processing_jobs', 'videos', ['video_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'processing_jobs', type_='foreignkey')
    op.create_foreign_key(op.f('processing_jobs_video_id_fkey'), 'processing_jobs', 'videos', ['video_id'], ['id'])
    # ### end Alembic commands ###
