"""add progress tracking to processing jobs

Revision ID: 7237d7da3655
Revises: 0baa5f1bac56
Create Date: 2026-07-26 16:00:31.876590

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7237d7da3655'
down_revision: Union[str, Sequence[str], None] = '0baa5f1bac56'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('processing_jobs', sa.Column('progress', sa.Integer(), nullable=False, server_default="0"))
    op.add_column('processing_jobs', sa.Column('current_step', sa.String(length=255), nullable=True))
    op.alter_column('processing_jobs', 'progress', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('processing_jobs', 'current_step')
    op.drop_column('processing_jobs', 'progress')
    # ### end Alembic commands ###
