"""configure cascade delete relationships

Revision ID: 98fe6f97d0c4
Revises: 21618627fcc5
Create Date: 2026-07-30 00:56:28.944779

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '98fe6f97d0c4'
down_revision: Union[str, Sequence[str], None] = '21618627fcc5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('chapters_video_id_fkey'), 'chapters', type_='foreignkey')
    op.create_foreign_key(None, 'chapters', 'videos', ['video_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('chat_histories_user_id_fkey'), 'chat_histories', type_='foreignkey')
    op.drop_constraint(op.f('chat_histories_video_id_fkey'), 'chat_histories', type_='foreignkey')
    op.create_foreign_key(None, 'chat_histories', 'videos', ['video_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'chat_histories', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('flashcards_video_id_fkey'), 'flashcards', type_='foreignkey')
    op.create_foreign_key(None, 'flashcards', 'videos', ['video_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('quizzes_video_id_fkey'), 'quizzes', type_='foreignkey')
    op.create_foreign_key(None, 'quizzes', 'videos', ['video_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('summaries_video_id_fkey'), 'summaries', type_='foreignkey')
    op.create_foreign_key(None, 'summaries', 'videos', ['video_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('translations_video_id_fkey'), 'translations', type_='foreignkey')
    op.create_foreign_key(None, 'translations', 'videos', ['video_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('videos_owner_id_fkey'), 'videos', type_='foreignkey')
    op.create_foreign_key(None, 'videos', 'users', ['owner_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'videos', type_='foreignkey')
    op.create_foreign_key(op.f('videos_owner_id_fkey'), 'videos', 'users', ['owner_id'], ['id'])
    op.drop_constraint(None, 'translations', type_='foreignkey')
    op.create_foreign_key(op.f('translations_video_id_fkey'), 'translations', 'videos', ['video_id'], ['id'])
    op.drop_constraint(None, 'summaries', type_='foreignkey')
    op.create_foreign_key(op.f('summaries_video_id_fkey'), 'summaries', 'videos', ['video_id'], ['id'])
    op.drop_constraint(None, 'quizzes', type_='foreignkey')
    op.create_foreign_key(op.f('quizzes_video_id_fkey'), 'quizzes', 'videos', ['video_id'], ['id'])
    op.drop_constraint(None, 'flashcards', type_='foreignkey')
    op.create_foreign_key(op.f('flashcards_video_id_fkey'), 'flashcards', 'videos', ['video_id'], ['id'])
    op.drop_constraint(None, 'chat_histories', type_='foreignkey')
    op.drop_constraint(None, 'chat_histories', type_='foreignkey')
    op.create_foreign_key(op.f('chat_histories_video_id_fkey'), 'chat_histories', 'videos', ['video_id'], ['id'])
    op.create_foreign_key(op.f('chat_histories_user_id_fkey'), 'chat_histories', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'chapters', type_='foreignkey')
    op.create_foreign_key(op.f('chapters_video_id_fkey'), 'chapters', 'videos', ['video_id'], ['id'])
    # ### end Alembic commands ###
