"""add user and video models

Revision ID: cfa58af66763
Revises: a1613be8b18c
Create Date: 2026-07-09 16:14:28.053966

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cfa58af66763'
down_revision: Union[str, Sequence[str], None] = 'a1613be8b18c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.add_column('videos', sa.Column('language', sa.String(length=20), nullable=False))
    op.add_column('videos', sa.Column('duration', sa.Integer(), nullable=False))
    op.add_column('videos', sa.Column('status', sa.String(length=30), nullable=False))
    op.add_column('videos', sa.Column('owner_id', sa.Integer(), nullable=False))
    op.add_column('videos', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False))
    op.alter_column('videos', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.create_unique_constraint(None, 'videos', ['filename'])
    op.create_foreign_key(None, 'videos', 'users', ['owner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'videos', type_='foreignkey')
    op.drop_constraint(None, 'videos', type_='unique')
    op.alter_column('videos', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.drop_column('videos', 'updated_at')
    op.drop_column('videos', 'owner_id')
    op.drop_column('videos', 'status')
    op.drop_column('videos', 'duration')
    op.drop_column('videos', 'language')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
